services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pigeon
      POSTGRES_PASSWORD: pigeon
      POSTGRES_DB: pigeon
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
